name: PR Test

on:
  pull_request:
    branches: ["main"]
    paths-ignore: ["**.md", "LICENSE", ".gitignore", ".github/ISSUE_TEMPLATE/**"]

env:
  NODE_OPTIONS: "--max-old-space-size=4096"
  TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
  TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-latest
            name: "Windows x64"
            args: ""

          - platform: macos-latest
            name: "macOS Universal"
            args: "--target universal-apple-darwin"

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v6.1.0
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 24
          cache: ""

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # 这个 target 仅在 macOS 上使用，因此将其放在 if 语句中，以稍微加快 Windows 和 Linux 的构建速度
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        uses: tauri-apps/tauri-action@v1.0.0
        with:
          args: ${{ matrix.args }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
